version: '3'
services:
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf.template
            - ./logs:/var/log/nginx
            - ${APP_PATH}:/app
        ports:
            - ${NGINX_PORT}:80
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/ash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
        depends_on:
            - php
    php:
        image: mp091689/php:latest
        restart: always
        volumes:
            - ${APP_PATH}:/app
        depends_on:
            - db
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - 3306:3306
        volumes:
            - ./db/mysql:/var/lib/mysql